### ISSUE TITLE
Database migration error

### ISSUE THREAD

**Issue by tienthanh2509** [mirego/killswitch#17]
Hi team,

Thank for your great app but it is unable to create a new database schema using the docker image

Please check

- Missing version for `ActiveRecord::Migration`
- Unable to create the database from migrations

Workaround by
- `bundle exec rake db:schema:load` instead of `bundle exec rake db:migrate` for the first time

**Comment by remi** [comment]
Hi Phạm Tiến Thành,

Can you produce a list of the exact steps you did to reproduce the problem?

Thank you!

**Comment by tienthanh2509** [comment]
Hi @remi 

Sorry for the late response, this issue only affects first-time installation.
- When data migrate is empty, killswitch docker unable to create tables
- After the first time deployed, the database contains the tables, and the docker container works normally

Error log

```
docker-compose up killswitch
[+] Running 2/2
 ⠿ Container killswitch-postgresql-1  Running                                                                                                                       0.0s
 ⠿ Container killswitch-1  Created                                                                                                                       0.7s
Attaching to killswitch-1
killswitch-1  | Executing migrations…
killswitch-1  | rake aborted!
killswitch-1  | StandardError: An error has occurred, this and all later migrations canceled:
killswitch-1  | 
killswitch-1  | Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
killswitch-1  | 
killswitch-1  |   class CreateApplications < ActiveRecord::Migration[4.2]
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:559:in `inherited'
killswitch-1  | /opt/killswitch/db/migrate/20131108183954_create_applications.rb:1:in `<main>'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
killswitch-1  | /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1045:in `load_migration'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1041:in `migration'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1037:in `disable_ddl_transaction'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1387:in `use_transaction?'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1379:in `ddl_transaction'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1302:in `each'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1302:in `migrate_without_lock'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1251:in `block in migrate'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1397:in `with_advisory_lock'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1251:in `migrate'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1086:in `up'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1061:in `migrate'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/railties/databases.rake:90:in `each'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'
killswitch-1  | /usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
killswitch-1  | /usr/local/bin/bundle:23:in `load'
killswitch-1  | /usr/local/bin/bundle:23:in `<main>'
killswitch-1  | 
killswitch-1  | Caused by:
killswitch-1  | StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
killswitch-1  | 
killswitch-1  |   class CreateApplications < ActiveRecord::Migration[4.2]
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:559:in `inherited'
killswitch-1  | /opt/killswitch/db/migrate/20131108183954_create_applications.rb:1:in `<main>'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
killswitch-1  | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
killswitch-1  | /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1045:in `load_migration'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1041:in `migration'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1037:in `disable_ddl_transaction'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1387:in `use_transaction?'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1379:in `ddl_transaction'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1302:in `each'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1302:in `migrate_without_lock'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1251:in `block in migrate'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1397:in `with_advisory_lock'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1251:in `migrate'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1086:in `up'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/migration.rb:1061:in `migrate'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/railties/databases.rake:90:in `each'
killswitch-1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'
killswitch-1  | /usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
killswitch-1  | /usr/local/bin/bundle:23:in `load'
killswitch-1  | /usr/local/bin/bundle:23:in `<main>'
killswitch-1  | Tasks: TOP => db:migrate
killswitch-1  | (See full trace by running task with --trace)
killswitch-1 exited with code 1
```

Thank you

**Comment by remi** [comment]
@tienthanh2509 Version 1.0.5 should fix this! 🎉
